#
# Protobuf
#

version: 3.0.0-preview{build}

branches:
  except:
    - gh-pages

os: Visual Studio 2015

matrix:
  fast_finish: true

platform: x86
configuration: Release

before_build: before_build.cmd

build_script: build.cmd

after_build: after_build.cmd

before_package: pack.cmd

artifacts:
  - path: 'artifacts\*.nupkg'
